// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

'use client';

import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ThemeProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import { AppBar, Toolbar, Typography, Button, Container, Box } from '@mui/material'
import { Toaster } from 'react-hot-toast'
import { theme } from './theme'
import MenuBookIcon from '@mui/icons-material/MenuBook'
import LightbulbIcon from '@mui/icons-material/Lightbulb'
import LocationOnIcon from '@mui/icons-material/LocationOn'
import { useEffect } from 'react'
import AOS from 'aos'
import 'aos/dist/aos.css'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    AOS.init({
      duration: 800,
      once: true,
      easing: 'ease-out-cubic',
    })
  }, [])

  return (
    <html lang="es">
      <body className={inter.className} id="__next">
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Toaster position="top-right" />
          
          <AppBar position="sticky" elevation={2} className="bg-gradient-to-r from-blue-600 to-violet-600">
            <Toolbar>
              <Link href="/" style={{ textDecoration: 'none', color: 'inherit', display: 'flex', alignItems: 'center' }}>
                <MenuBookIcon sx={{ mr: 2, fontSize: 32 }} />
                <Typography variant="h5" component="div" sx={{ fontWeight: 700 }}>
                  Librería Virtual
                </Typography>
              </Link>
              
              <Box sx={{ flexGrow: 1 }} />
              
              <Box sx={{ display: 'flex', gap: 1 }}>
                <Link href="/libros" passHref legacyBehavior>
                  <Button 
                    color="inherit" 
                    startIcon={<MenuBookIcon />}
                    sx={{ '&:hover': { bgcolor: 'rgba(255,255,255,0.1)' } }}
                  >
                    Libros
                  </Button>
                </Link>
                <Link href="/sugerencias" passHref legacyBehavior>
                  <Button 
                    color="inherit" 
                    startIcon={<LightbulbIcon />}
                    sx={{ '&:hover': { bgcolor: 'rgba(255,255,255,0.1)' } }}
                  >
                    Sugerencias
                  </Button>
                </Link>
                <Link href="/lugares" passHref legacyBehavior>
                  <Button 
                    color="inherit" 
                    startIcon={<LocationOnIcon />}
                    sx={{ '&:hover': { bgcolor: 'rgba(255,255,255,0.1)' } }}
                  >
                    Lugares
                  </Button>
                </Link>
              </Box>
            </Toolbar>
          </AppBar>

          <Box component="main" sx={{ minHeight: 'calc(100vh - 200px)', bgcolor: 'background.default', py: 4 }}>
            {children}
          </Box>

          <Box component="footer" sx={{ bgcolor: 'grey.900', color: 'white', py: 4, mt: 6 }}>
            <Container>
              <Typography variant="body1" align="center">
                © 2025 Librería Virtual. Todos los derechos reservados.
              </Typography>
            </Container>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  )
}
